/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  // JoinUsSidebar: [
  //   {
  //     type: 'category',
  //     label: 'Join us',
  //     items: [ "JoinTheTeam", "MaintainersRequirements", 'DeviceRequirements', "Guidelines"],
  //   },
  // ],

  // SupportSideBar: [
  //   {
  //     type: 'doc',
  //     label: 'Frequently Asked Questions',
  //     id: 'faq',
  //   },
  //   {
  //     type: 'doc',
  //     label: 'Community Guidelines',
  //     id: 'CommunityGuidelines',
  //   },
  //   {
  //     type: 'category',
  //     label: 'Guides',
  //     items: ["BugReport", "HowToLog"],
  //   }
  // ],

  WelcomeSidebar: [
    {
      type: "doc",
      label: "Welcome",
      id: "welcome"
    },
    {
      type: "category",
      label: "For Users",
      
      items: [
        {
          type: 'doc',
          label: 'Frequently Asked Questions',
          id: 'faq',
        },
        {
          type: 'doc',
          label: 'Community Guidelines',
          id: 'CommunityGuidelines',
        },
        {
          type: 'category',
          label: 'Guides',
          items: ["BugReport", "HowToLog"],
      }
      ]
    },
    {
      type: 'category',
      label: 'For Maintainers',
      items: [
        {
          type: 'category',
          label: 'Join us',
          link: {
            type: 'doc',
            id: 'JoinUs/index',
          },
          items: [ "JoinUs/MaintainersRequirements", 'JoinUs/DeviceRequirements', "JoinUs/Guidelines"],
        },
      ]
    }
  ]

};

module.exports = sidebars;
