/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  MaintainersSidebar: [
    {
      type: 'category',
      label: 'Join The Team',
      link: {type: 'doc', id: 'JoinTheTeam/JoinTheTeam'},
      items: ["JoinTheTeam/MaintainersRequirements", "JoinTheTeam/DeviceRequirements"],
    },
    {
      type: "category",
      label: "Building PixelOS",
      items: ["BuildingPixelOS/BuildGuide"]
    }
  ],

  SupportSideBar: [
    {
      type: 'doc',
      label: 'Frequently Asked Questions',
      id: 'ForUsers/faq',
    },
    {
      type: 'doc',
      label: 'Community Guidelines',
      id: 'ForUsers/CommunityGuidelines',
    },
    {
      type: 'category',
      label: 'Guides',
      items: ["guides/BugReport", "guides/HowToLog", "guides/HowToRoot"],
    }
  ],

  // DonateSidebar: [
  //   {
  //     type: 'doc',
  //     label: 'Donate',
  //     id: 'donate/donate',
  //   },
  // ],

  ResourcesSideBar: [
    {
      type: 'doc',
      label: "Important Links",
      id: "resources/ImportantLinks",
    },
    {
      type: 'doc',
      label: "Banners Archive",
      id: "resources/Banners"
    },
    {
      type: 'doc',
      label: "Wallpapers",
      id: "resources/Wallpapers"
    },
  ]

};

module.exports = sidebars;
